Write-Host "== Doppler Bootstrap =="
Write-Host "1) Install CLI:  curl -sLf https://cli.doppler.com/install.sh | sh"
Write-Host "2) Login:        doppler login --token <DOPPLER_SERVICE_TOKEN_ADMIN>"
Write-Host "3) Create proj/envs (idempotent):"
Write-Host "   doppler projects create tippy || true"
Write-Host "   doppler environments create development --project tippy || true"
Write-Host "   doppler environments create staging --project tippy || true"
Write-Host "   doppler environments create production --project tippy || true"
Write-Host "4) Create CI read-only token:"
Write-Host "   doppler service-token create --name ci-token --role read_only --environments development,staging --project tippy"
Write-Host "5) Add to GitHub Actions as DOPPLER_TOKEN_CI (Settings → Secrets → Actions)."
Write-Host "6) Set required keys in each env (example):"
Write-Host "   doppler secrets set TIPPY_DB_URL='...' --project tippy --config development"

