# Kubernetes example: Using Doppler via init container
# Ledger Reference: Tippy Decision Ledger v1.0 (Final), ยง 25
# 
# NOTE: This is an example. Prefer Doppler's Kubernetes Operator or sidecar pattern.
# Do not create Kubernetes secrets with plaintext values unless absolutely necessary.

apiVersion: v1
kind: Secret
metadata:
  name: doppler-token
  namespace: tippy
type: Opaque
stringData:
  # This should be set via kubectl create secret or sealed-secrets
  # NEVER commit the actual token value
  doppler-token: "dp.st.xxxxx"  # Replace with actual token via kubectl

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tippy-api
  namespace: tippy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tippy-api
  template:
    metadata:
      labels:
        app: tippy-api
    spec:
      initContainers:
      - name: doppler-setup
        image: dopplerhq/cli:latest
        command: ['sh', '-c']
        args:
          - |
            doppler login --token "$(cat /secrets/doppler-token)"
            doppler secrets download --no-file --format env-no-quotes > /shared/env
        volumeMounts:
        - name: doppler-token
          mountPath: /secrets
          readOnly: true
        - name: shared-env
          mountPath: /shared
      containers:
      - name: tippy-api
        image: tippy-api:latest
        envFrom:
        - configMapRef:
            name: tippy-config
        env:
        - name: DOPPLER_ENVIRONMENT
          value: "production"
        volumeMounts:
        - name: shared-env
          mountPath: /shared
          readOnly: true
      volumes:
      - name: doppler-token
        secret:
          secretName: doppler-token
      - name: shared-env
        emptyDir: {}

---
# Alternative: Use Doppler Kubernetes Operator (recommended)
# See: https://docs.doppler.com/docs/kubernetes-operator

